  	<!-- 1140px Grid styles for IE -->
	<!--[if lte IE 9]><link rel="stylesheet" href="https://www.71lbs.com/assets/ie.css" type="text/css" media="screen" /><![endif]-->
	<!-- The 1140px Grid - http://cssgrid.net/ -->
	<link rel="stylesheet" href="https://www.71lbs.com/assets/1140.css" type="text/css" media="screen" />
  <!-- Jquery ui styles -->
	<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/redmond/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />
  	<!-- Your styles -->
	<link rel="stylesheet" href="https://www.71lbs.com/assets/businesses.css" type="text/css" media="screen" />	
	<link rel="stylesheet" href="https://www.71lbs.com/assets/style.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="https://www.71lbs.com/assets/users.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="https://www.71lbs.com/assets/signup.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="https://www.71lbs.com/assets/signup2.css" type="text/css" media="screen" />
    <!-- JS libraries -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script type="text/javascript">
// <![CDATA[
   // noConflict so we can use both libraries
   var $j = jQuery.noConflict();
//]]>
</script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
   <script type="text/javascript">
   //Google API charts
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawChart);
      function drawChart() {
		  var data = new google.visualization.DataTable();
		  //Add number of Columns
		  data.addColumn('string', 'Month');
		  data.addColumn('number', 'Refund');
		  
		  var monthNames = [ "January", "February", "March", "April", "May", "June",
		  "July", "August", "September", "October", "November", "December" ];
		
		//get first month and last month since business started
		 //if not fedex refunds is empty				
				
		//loop to display a chart with all the months since 
		//business started in current year
        for (var i = <?php echo $result->first_month; ?>; i <= <?php echo $result->
last_month; ?>; i++) {		
			data.addRow([monthNames[i - 1],0]);//Add a row for each refund by month key
		}

		//Design chart
	    var options = {
      		title: 'Total of Refunds Month over Month',
      		titleTextStyle: {color:'979797', fontSize: 12},
      		hAxis: {title: 'Month', titleTextStyle: {color: '979797', fontSize: 12}},
      		vAxis: {title: 'Economic Value of Refunds Revenue', titleTextStyle: {color: '979797', fontSize: 12}, minValue:0, maxValue:<?php echo
$result->max_value; ?>},
	        fontName: 'Arial, Helvetica, sans-serif',
	        animation: { duration: 1000, easing: 'out'}
    	};
		
	    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
		chart.draw(data, options);

		//create animation of bars going up
		//Get hash of total refunds by months for fedex
		 //if not fedex empty do foreach
         <?php if ($result->fdx_monthly_refunds): ?>
		setTimeout(function(){        		
            <?php foreach ($result->fdx_monthly_refunds as $key => $value): ?>
                data.setValue(<?php echo $value[0]; ?> - <?php echo $result->
first_month; ?>,1,<?php echo
$value[1] ?>); //setValue(row index,column index, value)
            <?php endforeach ?>        		
			chart.draw(data, options);
			},500);
        <?php endif ?>

		//create animation of bars going up
		//Get hash of total refunds by months for ups
		 //if not ups empty do foreach
		<?php if ($result->ups_monthly_refunds): ?>
        setTimeout(function(){
            
                <?php foreach ($result->ups_monthly_refunds as $key => $value): ?>
                	var preValue = data.getValue(<?php echo $value[0]; ?> - <?php echo
$result->first_month; ?>,1); //get value thats there now and add it to next value
            		data.setValue(<?php echo $value[0]; ?> - <?php echo $result->
first_month; ?>,1,<?php echo
$value[1] ?> + preValue); //setValue(row index,column index, value)
                <?php endforeach ?>
			chart.draw(data, options);
			},2500);
        <?php endif ?>        		        

      }
      
	  </script>
<script>

  $j(function() {
	
  	
  	<!-- Jquery ui datepicker -->
    $j( "#fdx_from" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 1,
      maxDate: -1,
      autoSize: true,      
      onClose: function( selectedDate ) {
        $j( "#fdx_to" ).datepicker( "option", "minDate", selectedDate );
      },
      onSelect: function()
      {
           if ($j("#fdx_to").datepicker("getDate") != null)
              getDataForRange("fdx");              
      }
    });
    
    $j( "#fdx_to" ).datepicker({
         defaultDate: "+1w",
         changeMonth: true,
         numberOfMonths: 1,
         maxDate: 0,
         autoSize: true,
         onClose: function( selectedDate ) {
            $j( "#fdx_from" ).datepicker( "option", "maxDate", selectedDate );              
         },
         onSelect: function()
         {
           if ($j("#fdx_from").datepicker("getDate") != null)
              getDataForRange("fdx");              
         }
     });     
     
     $j( "#ups_from" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 1,
      maxDate: -1,
      autoSize: true,
      onClose: function( selectedDate ) {
        $j( "#ups_to" ).datepicker( "option", "minDate", selectedDate );
      },
      onSelect: function()
      {
           if ($j("#ups_to").datepicker("getDate") != null)
              getDataForRange("ups");              
      }
    });
    
    $j( "#ups_to" ).datepicker({
         defaultDate: "+1w",
         changeMonth: true,
         numberOfMonths: 1,
         maxDate: 0,
         autoSize: true,
         onClose: function( selectedDate ) {
            $j( "#ups_from" ).datepicker( "option", "maxDate", selectedDate );              
         },
         onSelect: function()
         {
           if ($j("#ups_from").datepicker("getDate") != null)
              getDataForRange("ups");              
         }
     }); 
     
     $j(".profile_li").hover(
  	function() {
  		$j(".profile_li").css({'background-color': '#ffffff', 'border-color': '#ffffff'});
  		$j(this).css({'background-color': '#FDFDFD', 'border-color': '#ECE3E3'})
  	},
  	function() {
  		$j(".profile_li").css({'background-color': '#ffffff', 'border-color': '#ffffff'});  		
  	}
  );      
  });
  
  function getDataForRange(acnt_type)
  {
  	if (acnt_type == "fdx") {
  	  var fromDate = $j("#fdx_from").datepicker("getDate");
  	  var toDate = $j("#fdx_to").datepicker("getDate");
  	}
  	else {
  	  var fromDate = $j("#ups_from").datepicker("getDate");
  	  var toDate = $j("#ups_to").datepicker("getDate");	
  	}  	  
  	
  	fromDate = $j.datepicker.formatDate('mm-dd-yy', fromDate);  	
  	toDate = $j.datepicker.formatDate('mm-dd-yy', toDate);
  	
  	var json = { "id":"<?php echo $result->business_id ?>","from":fromDate, "to":toDate, "acnt":acnt_type, "callback":"data" };
    var sid ="<?php echo $result->business_id ?>";
    my_url = "https://54.221.203.199/api/session/selectRefundRange.jsonp?id="+ sid +"&from=" + fromDate + "&to="+toDate+"&acnt="+acnt_type+"&callback=data";    
    
		$j.ajaxSetup({
		error: function(jqXHR, exception) {
			if (jqXHR.status === 0) {
				alert('Not connect.\n Verify Network.');
			} else if (jqXHR.status == 404) {
				alert('Requested page not found. [404]');
			} else if (jqXHR.status == 500) {
				alert('Internal Server Error [500].');
			} else if (exception === 'parsererror') {
				alert('Requested JSON parse failed.');
			} else if (exception === 'timeout') {
				alert('Time out error.');
			} else if (exception === 'abort') {
				alert('Ajax request aborted.');
			} else {
				alert('Uncaught Error.\n' + jqXHR.responseText);
			}
		}
	});
  	
  	$j.ajax({
        url: my_url,
        type: "GET",
        dataType: "jsonp",
        success: function (result) {           
           if (acnt_type == "fdx")
             populateFedexTable(result);   
           else
             populateUpsTable(result);                   
        },
        error: function (req, msg, obj) {
           alert("The requested data could not be processed "+ msg);
        }
    });   

  }
  
  function populateFedexTable(result)
  {  	 
       if (result.totalRefunds > 0) {
  	 	fedexRefunds = result.refunds;
  	 	//links = result.links
  	    dates = result.datesArray;
  	    $j("#fdx").empty();  	
  	    count = 1;
        
        $j.each( fedexRefunds, function( i, value ) {    
          	       //url = '&nbsp; &nbsp;';
  	       
  	       //if(links[i] != '-1')
  	       	//url = "<a href='" +links[i] +"'>refund capture</a>";          
  	       
  	       if (count) { //Appended elements belong to class 'even', use for background color white  	       		
  	       			
  	 	     $j("#fdx").append("<span class='even f_acnt'>"+fedexRefunds[i].payer_acnt+
  	 	   					  "</span><span class='even f_track'>"+fedexRefunds[i].tracking+
  	 	   					  "</span><span class='even f_date'>"+dates[i]+"</span><span class='even f_ref'>"+
  	 	   					  fedexRefunds[i].refund_amt+"</span><br />");// <span class='even f_acnt'>"+ url +"</span><br />");                                        
  	 	   	 count = 0;
  	 	   }
  	 	   else { //Appended elements belong to class 'prime', use for background color gray
  	 	   	$j("#fdx").append("<span class='prime f_acnt'>"+fedexRefunds[i].payer_acnt+
  	 	   					  "</span><span class='prime f_track'>"+fedexRefunds[i].tracking+
  	 	   					  "</span><span class='prime f_date'>"+dates[i]+"</span><span class='prime f_ref'>"+
  	 	   					  fedexRefunds[i].refund_amt+"</span><br />");// <span class='prime f_acnt'>"+ url +"</span><br />");                              
  	 	   	count = 1;
  	 	   }        
        });
  	    
  	    $j(".dash-wrapper").height($j(".dash-right").height() + 300); //recalculate new height for wrapper
  		$j(".vertical2").height($j(".dash-wrapper").height() - 290);  //recalculate new height for image
  	 
  	    $j("#refundsFdx").html("$"+result.totalRefunds);
  	 }
  	 else {
  	 	$j(alert("There are no refunds available for the selected dates"));
  	 } 	 
  }
  
  function populateUpsTable(result)
  {
  	 if (result.totalRefunds > 0) {
  	 	upsRefunds = result.refunds;
  	    dates = result.datesArray;
  	    $j("#ups").empty();
  	    count = 1;
        
        $j.each( upsRefunds, function( i, value ) {
  	       if (count) {
  	 	      $j("#ups").append("<span class='even f_acnt'>"+upsRefunds[i].acnt_nbr+"</span><span class='even f_track'>"+
  	 	      				   upsRefunds[i].tracking+"</span><span class='even f_date'>"+dates[i]+
  	 	      				   "</span><span class='even f_inv'>"+upsRefunds[i].invoice_nbr+
  	 	      				   "</span><span class='even f_ref'>"+upsRefunds[i].refund_amt+"</span><br />");
  	 		  count = 0;
  	 	   }
  	 	   else {
  	 	   	   $j("#ups").append("<span class='even f_acnt'>"+upsRefunds[i].acnt_nbr+"</span><span class='even f_track'>"+
  	 	      				   upsRefunds[i].tracking+"</span><span class='even f_date'>"+dates[i]+
  	 	      				   "</span><span class='even f_inv'>"+upsRefunds[i].invoice_nbr+
  	 	      				   "</span><span class='even f_ref'>"+upsRefunds[i].refund_amt+"</span><br />");
  	 	       count = 1;
  	 	   } 	    
        
        });
  	 
  	    $j(".dash-wrapper").height($j(".dash-right").height() + 300); //recalculate new height for wrapper
  		$j(".vertical2").height($j(".dash-wrapper").height() - 290);  //recalculate new height for image
  	    $j("#refundsUps").html("$"+result.totalRefunds);
  	 }
  	 else {
  	 	$j(alert("There are no refunds available for the selected dates"));
  	 } 	 
  }
  
  
 
	//mimic folder tabs to display graph and table
	$j(document).ready(function() {
	    $j("#content").children("div").hide(); // Initially hide all content
	    $j("#tabs li:first").attr("id","current"); // Activate first tab
	    $j("#content div:first").fadeIn(); // Show first tab content
	    
	    $j('#tabs a').click(function(e) {
	        e.preventDefault();
	        if ($j(this).closest("li").attr("id") == "current"){ //detection for current tab
	         return       
	        }
	        else{             
	        $j("#content").children("div").hide(); //Hide all content
	        $j("#tabs li").attr("id",""); //Reset id's
	        $j(this).parent().attr("id","current"); // Activate this
	        $j('#' + $j(this).attr('name')).fadeIn(); // Show content for current tab
	        }
	    });
	});
  //Business profile selections
</script>

<form autocomplete="off"> 

<div class="dash-wrapper">
                
 <span class="b_name"><?php echo $result->business_name ?></span>
 <div style="clear:both"></div>
 
 <div class="dash-left">
 <!-- Void -->
 </div><!-- end dash-left -->
 <div class="vertical1"></div>
 <!--<div class="vertical2"></div>-->

 <div class="dash-right">
 	<div id="ref_content" class="contents" style="overflow:hidden">
 		<span class="welcome">Welcome to 71 Pounds</span>
 		<div class="yr_date">Year to date refunds: <?php echo $result->yearly_total ?></div>
 		  <?php if ($result->yearly_total > 0): ?>	  
			<p class="last_updated_refunds">Last updated:  <?php echo $result->last_update ?></p>
		  <?php endif ?>
 	      
 	    <div id="dataChartsTables"> 
 	    	<ul id="tabs">
    			<li><a href="#" name="tab1">Graph</a></li>
    			<li><a href="#" name="tab2">Table</a></li>
			</ul>
 	      	
 	      	<div id="content"> 
			    
			    <div id="tab1">
			    	<div id="chart_div"></div>
		    	</div><!-- tab1 -->
			    
			    <div id="tab2">
		 			<div class="totals">
			 			<span class="f_this"> <?php echo ($result->fdx_this_month); ?> </span>
			 			<span class="f_last"><?php echo ($result->fdx_prev_month); ?> </span>
			 			<span class="f_year"><?php echo ($result->yearly_fdx_ref); ?> </span>
			 			<span class="u_this"><?php echo ($result->ups_this_month); ?> </span>
			 			<span class="u_last"><?php echo ($result->ups_prev_month); ?> </span>
			 			<span class="u_year"><?php echo ($result->yearly_ups_ref); ?> </span>
			 			<span class="t_this"><?php echo ($result->month_total); ?> </span>
			 			<span class="t_last"><?php echo ($result->prev_total); ?> </span>
			 			<span class="t_year"><?php echo($result->yearly_total); ?> </span>
		 			</div>
	 			</div><!-- tab2 -->
 			</div>	 
 		</div>
 		
 			<?php if ($result->fdx_uname !== null && $result->fdx_uname != ""): ?>
		<span class="f_latest">Current month activity - FedEx</span>
		<div style="margin-top: 50px"></div>
		<div style="width:790px">
		<div class="acnt_tbl2" style="border-left:1px solid #DADADA;width:140px">Account Number</div>
		<div class="acnt_tbl2" style="width:140px;padding-left:50px">Tracking</div>
		<div class="acnt_tbl2" style="width:85px">Date</div>
		<div class="acnt_tbl2" style="width:130px;padding-left: 30px">Refund Amount</div> 		
		<div style="clear:both"></div>

		<div id="fdx">
		<?php $count = 0 ?>
		<?php foreach ($result->fedex_refunds as $key => $value): ?>
			<?php if ($count == 0): ?>
				<span class="even f_acnt"><?php echo $value->payer_acnt ?></span>
				<span class="even f_track"><?php echo $value->tracking ?></span>
				<span class="even f_date"><?php echo $value->invoice_dt ?></span>
				<span class="even f_ref">$<?php echo $value->refund_amt ?></span>

			<?php $count = 1 ?>
			<?php else: ?>
				<span class="prime f_acnt"><?php echo $value->payer_acnt ?></span>
				<span class="prime f_track"><?php echo $value->tracking ?></span>
				<span class="prime f_date"><?php echo $value->invoice_dt ?></span>
				<span class="prime f_ref">$<?php echo $value->refund_amt ?></span>
				<?php $count = 0 ?>
			<?php endif ?>
		<?php endforeach ?>	
		<div style="clear:both"></div>	

	</div>
	<div style="clear:both"></div>
	<div class="totals_div1">
	<span style="margin-left: 360px;">Total Refunds</span>		   
	</div>
	<div class="totals_div2">	
	<span id="refundsFdx" class="f_total"><?php echo $result->fdx_this_month ?></span>
	</div>
	</div>
	<span class="from">From</span>
	<input type="text" id="fdx_from" class="date_input" />
	<span>to</span>
	<input type="text" id="fdx_to" class="date_input" />
    <?php endif ?>
    <br/>
    	<?php if ($result->ups_uname !== null && $result->ups_uname != ""): ?>
		<span class="f_latest">Current month activity - UPS</span>
		<div style="margin-top: 50px"></div>
		
		<div style="width:900px">
 		<div class="acnt_tbl2" style="border-left:1px solid #DADADA;width:140px">Account Number</div>
 		<div class="acnt_tbl2" style="width:160px;padding-left:30px">Tracking</div>
 		<div class="acnt_tbl2" style="width:85px">Date</div>
 		<div class="acnt_tbl2" style="width:130px;padding-left:30px">Invoice Number</div>
 		<div class="acnt_tbl2" style="width:130px;padding-left: 30px">Refund Amount</div>
 		<div style="clear:both"></div>
		
		<div id="ups">
		<?php $count = 0 ?>		
		<?php foreach ($result->ups_refunds as $key => $value): ?>
		  <?php if ($count == 0): ?>
		  		<span class="even f_acnt"><?php echo $value->acnt_nbr ?></span>
		  		<span class="even f_track"><?php echo $value->tracking ?></span>
		  		<span class="even f_date"><?php echo $value->invoice_dt ?></span>
		  		<span class="even f_inv"><?php echo $value->invoice_nbr ?></span>
		  		<span class="even f_ref">$<?php echo $value->refund_amt ?></span>
		  		<?php $count = 1 ?>
		  <?php else: ?>
		  		<span class="prime f_acnt"><?php echo $value->acnt_nbr ?></span>
		  		<span class="prime f_track"><?php echo $value->tracking ?></span>
		  		<span class="prime f_date"><?php echo $value->invoice_dt ?></span>
		  		<span class="prime f_inv"><?php echo $value->invoice_nbr ?></span>
		  		<span class="prime f_ref">$<?php echo $value->refund_amt ?></span>
		  		<?php $count = 0 ?>
		  <?php endif ?>
		  <div style="clear:both"></div>
		<?php endforeach ?>	
		</div>
		</div>
		<div style="clear:both"></div>
		<div class="totals_div1" style="width:623px">
		   <span style="margin-left:520px;">Total Refunds</span>		   
		</div>
		<div class="totals_div2" style="margin-left:630px">
			<span id="refundsUps" class="f_total"><?php echo $result->ups_this_month ?></span>
		</div>
		
		<span class="from">From</span>
  		<input type="text" id="ups_from" class="date_input" />
		<span>to</span>
		<input type="text" id="ups_to" class="date_input" />
	<?php endif ?>
		
 	</div> <!-- end refunds -->
 	
 	<!-- Accounts -->
 	<div id="acnt_content" class="contents" style="display:none">
	<!-- Void -->
 	</div>
 	
 	<!-- Users -->
 	<div id="usr_content" class="contents" style="display:none; overflow: hidden;">
	<!-- Void -->
 	</div> 	
 </div>	
</div>
<a href="https://www.71lbs.com/businesses/<?php echo $result->business_id ?>" target="_blank">More Information</a>
        
</form>		
<div id="test">
</div>