<?php
$email = $_POST['email'];
$password = $_POST['userPass'];

if($password === "")
    $password = "-1";    
$opts = array('http' => array(
        'method' => 'GET',
        'header' => 'Content-type: application/json',
        'content' => '{"email": "' . $email . '","password":"' . $password .
            '", "signup":"true"}'));            

$context = stream_context_create($opts);

$url = 'https://www.71lbs.com/api/session';
//$url = 'https://54.221.203.199/api/session';
//$url = 'http://localhost:3000/api/session';
//testing
//$url = 'http://localhost/test.json';
//$url = 'http://localhost/no_analytics.json';

$result = file_get_contents($url, false, $context);
$result = json_decode($result);

//debug
//var_dump($result);
//setlocale(LC_MONETARY, 'en_US');

if($result->error){
    echo("<div style='color: red'><b>Error:</b> " . $result->msj) . "</div>";
    echo '<a href="javascript:history.go(-1)" title="Back">&laquo; Go back</a>';
    exit();
} 
if ($result->analytics_is_active)
    require_once("_analytics.phtml");    
else
    require_once("_no_analytics.phtml");    
?>